"""Add app models_fixes2

Revision ID: 68a017df9129
Revises: c4193bb8eae0
Create Date: 2022-08-23 16:41:26.187508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a017df9129'
down_revision = 'c4193bb8eae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
